version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile

    network_mode: 'bridge'

    ports:
      - 8080:80

  app1:
    build:
      context: .
      dockerfile: app1.Dockerfile

