version: '3'

services:
  node-frontend:
    container_name: covid_tmp
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:8080"   # express
    volumes:
      - ./:/app

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    depends_on:
      - node-frontend
    ports:
      - "8080:80"       # http
    volumes:
      - ./public:/var/www/public:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro

#
#services:
##  bulk:
##    container_name: covid_tmp
##    build:
##      context: .
##      dockerfile: Dockerfile
##    volumes:
##      - '.:/app'
##      - '/app/node_modules'
##    expose:
##      - "8080"
##    ports:
##      - "8080:8080"
#
#  nginx:
#    image: nginx:latest
#    container_name: production_nginx
#    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "8080:3000"
#    expose:
#      - "8080"
#
#  web-app:
#    container_name: covid_tmp
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - '3000:3000'
#
